name: Pylint

on: [push, pull_request]

jobs:
  build:
    name: integrating pylint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        env:
          REPORT_ONLY: true
          SHOW_ERRORS: true
        run: |
          python -m pip install --upgrade pip
