FROM python:3.11-slim

RUN apt-get update && apt-get install -y sqlite3

WORKDIR /app

COPY . /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python /app/src/start_movies.py

# Use this command to keep the container running for testing
CMD ["tail", "-f", "/dev/null"]
