FROM python:3.11-slim

RUN apt-get update && apt-get install -y sqlite3

WORKDIR /database

COPY . /database

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN python /database/src/start_movies.py

# Use this command to keep the container running for testing
CMD ["tail", "-f", "/dev/null"]
